title: blog.bcrowthe.com
description: Some thoughts
theme: just-the-docs

url: https://blog.bcrowthe.com

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# External navigation links
nav_external_links:
  - title: Resume
    url: https://resume.bcrowthe.com
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
